import type * as Monaco from "monaco-editor";

let registered = false;

/** Register a lightweight HLSL language for Monaco (once per page load). */
export function registerHlslLanguage(monaco: typeof Monaco): void {
	if (registered) return;
	registered = true;

	monaco.languages.register({ id: "hlsl" });
	monaco.languages.setMonarchTokensProvider("hlsl", {
		defaultToken: "",
		keywords: [
			"break",
			"case",
			"const",
			"continue",
			"default",
			"discard",
			"do",
			"else",
			"extern",
			"false",
			"for",
			"if",
			"in",
			"inline",
			"inout",
			"out",
			"return",
			"static",
			"struct",
			"switch",
			"true",
			"uniform",
			"void",
			"while",
			"cbuffer",
			"register",
		],
		typeKeywords: [
			"bool",
			"float",
			"float2",
			"float3",
			"float4",
			"float2x2",
			"float3x3",
			"float4x4",
			"half",
			"half2",
			"half3",
			"half4",
			"int",
			"int2",
			"int3",
			"int4",
			"uint",
			"uint2",
			"uint3",
			"uint4",
			"matrix",
			"vector",
			"Texture2D",
			"SamplerState",
		],
		builtins: [
			"abs",
			"acos",
			"all",
			"any",
			"asin",
			"atan",
			"atan2",
			"ceil",
			"clamp",
			"clip",
			"cos",
			"cosh",
			"cross",
			"ddx",
			"ddy",
			"degrees",
			"distance",
			"dot",
			"exp",
			"exp2",
			"floor",
			"fmod",
			"frac",
			"length",
			"lerp",
			"log",
			"log2",
			"max",
			"min",
			"mul",
			"normalize",
			"pow",
			"radians",
			"reflect",
			"refract",
			"rsqrt",
			"saturate",
			"sign",
			"sin",
			"sinh",
			"smoothstep",
			"sqrt",
			"step",
			"tan",
			"tanh",
			"tex2D",
			"transpose",
		],
		semantics: [
			"SV_POSITION",
			"SV_Position",
			"SV_TARGET",
			"SV_Target",
			"SV_VertexID",
			"POSITION",
			"NORMAL",
			"TANGENT",
			"TEXCOORD0",
			"TEXCOORD1",
			"COLOR",
			"COLOR0",
		],
		operators: [
			"=",
			">",
			"<",
			"!",
			"~",
			"?",
			":",
			"==",
			"<=",
			">=",
			"!=",
			"&&",
			"||",
			"++",
			"--",
			"+",
			"-",
			"*",
			"/",
			"&",
			"|",
			"^",
			"%",
			"<<",
			">>",
		],
		symbols: /[=><!~?:&|+\-*/^%]+/,
		escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
		tokenizer: {
			root: [
				[
					/[a-zA-Z_]\w*/,
					{
						cases: {
							"@keywords": "keyword",
							"@typeKeywords": "type",
							"@builtins": "predefined",
							"@semantics": "annotation",
							"@default": "identifier",
						},
					},
				],
				{ include: "@whitespace" },
				[/[{}()[\]]/, "@brackets"],
				[/[<>](?!@symbols)/, "@brackets"],
				[
					/@symbols/,
					{
						cases: {
							"@operators": "operator",
							"@default": "",
						},
					},
				],
				[/\d*\.\d+([eE][-+]?\d+)?[fFhH]?/, "number.float"],
				[/\d+[eE][-+]?\d+[fFhH]?/, "number.float"],
				[/\d+[fFhH]/, "number.float"],
				[/0[xX][0-9a-fA-F]+/, "number.hex"],
				[/\d+/, "number"],
				[/[;,.]/, "delimiter"],
				[/"([^"\\]|\\.)*$/, "string.invalid"],
				[/"/, "string", "@string"],
			],
			whitespace: [
				[/[ \t\r\n]+/, "white"],
				[/\/\*/, "comment", "@comment"],
				[/\/\/.*$/, "comment"],
			],
			comment: [
				[/[^/*]+/, "comment"],
				[/\*\//, "comment", "@pop"],
				[/[/*]/, "comment"],
			],
			string: [
				[/[^\\"]+/, "string"],
				[/@escapes/, "string.escape"],
				[/\\./, "string.escape.invalid"],
				[/"/, "string", "@pop"],
			],
		},
	});
}
