import type * as Monaco from 'monaco-editor'

let registered = false

/** Monaco language id used by the geometry C# editor (avoids clobbering built-in csharp). */
export const CSHARP_GEOM_LANGUAGE_ID = 'csharp-geom'

export const GEOM_THEME_LIGHT = 'cloudea-geom-light'
export const GEOM_THEME_DARK = 'cloudea-geom-dark'

function defineGeomThemes (monaco: typeof Monaco): void {
  monaco.editor.defineTheme(GEOM_THEME_LIGHT, {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'keyword',
        foreground: 'AF00DB' },
      { token: 'type',
        foreground: '267F99',
        fontStyle: 'bold' },
      { token: 'predefined',
        foreground: '795E26' },
      { token: 'number',
        foreground: '098658' },
      { token: 'number.float',
        foreground: '098658' },
      { token: 'number.hex',
        foreground: '098658' },
      { token: 'string',
        foreground: 'A31515' },
      { token: 'string.escape',
        foreground: 'A31515' },
      { token: 'comment',
        foreground: '008000' },
      { token: 'delimiter',
        foreground: '6B6B6B' },
      { token: 'operator',
        foreground: '000000' },
    ],
    colors: {},
  })

  monaco.editor.defineTheme(GEOM_THEME_DARK, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'keyword',
        foreground: 'C586C0' },
      { token: 'type',
        foreground: '4EC9B0',
        fontStyle: 'bold' },
      { token: 'predefined',
        foreground: 'DCDCAA' },
      { token: 'number',
        foreground: 'B5CEA8' },
      { token: 'number.float',
        foreground: 'B5CEA8' },
      { token: 'number.hex',
        foreground: 'B5CEA8' },
      { token: 'string',
        foreground: 'CE9178' },
      { token: 'string.escape',
        foreground: 'CE9178' },
      { token: 'comment',
        foreground: '6A9955' },
      { token: 'delimiter',
        foreground: 'D4D4D4' },
      { token: 'operator',
        foreground: 'D4D4D4' },
    ],
    colors: {},
  })
}

/**
 * Richer C# highlighting for the geometry host:
 * built-in C# keywords + Terraria-like API types/members.
 */
export function registerCsharpLanguage (monaco: typeof Monaco): void {
  defineGeomThemes(monaco)
  if (registered) { return }
  registered = true

  monaco.languages.register({ id: CSHARP_GEOM_LANGUAGE_ID })

  monaco.languages.setLanguageConfiguration(CSHARP_GEOM_LANGUAGE_ID, {
    comments: {
      lineComment: '//',
      blockComment: ['/*', '*/'],
    },
    brackets: [
      ['{', '}'],
      ['[', ']'],
      ['(', ')'],
      ['<', '>'],
    ],
    autoClosingPairs: [
      { open: '{',
        close: '}' },
      { open: '[',
        close: ']' },
      { open: '(',
        close: ')' },
      { open: '\'',
        close: '\'',
        notIn: ['string', 'comment'] },
      { open: '"',
        close: '"',
        notIn: ['string', 'comment'] },
      { open: '/*',
        close: '*/',
        notIn: ['string'] },
    ],
    surroundingPairs: [
      { open: '{',
        close: '}' },
      { open: '[',
        close: ']' },
      { open: '(',
        close: ')' },
      { open: '\'',
        close: '\'' },
      { open: '"',
        close: '"' },
      { open: '<',
        close: '>' },
    ],
  })

  monaco.languages.setMonarchTokensProvider(CSHARP_GEOM_LANGUAGE_ID, {
    defaultToken: '',
    // No tokenPostfix — keep tokens as keyword/type/predefined for reliable theme matching
    keywords: [
      'abstract',
      'as',
      'base',
      'break',
      'case',
      'catch',
      'checked',
      'class',
      'const',
      'continue',
      'default',
      'delegate',
      'do',
      'else',
      'enum',
      'event',
      'explicit',
      'extern',
      'false',
      'finally',
      'fixed',
      'for',
      'foreach',
      'goto',
      'if',
      'implicit',
      'in',
      'interface',
      'internal',
      'is',
      'lock',
      'namespace',
      'new',
      'null',
      'operator',
      'out',
      'override',
      'params',
      'private',
      'protected',
      'public',
      'readonly',
      'ref',
      'return',
      'sealed',
      'sizeof',
      'stackalloc',
      'static',
      'struct',
      'switch',
      'this',
      'throw',
      'true',
      'try',
      'typeof',
      'unchecked',
      'unsafe',
      'using',
      'virtual',
      'volatile',
      'while',
      'async',
      'await',
      'dynamic',
      'nameof',
      'partial',
      'var',
      'when',
      'where',
      'yield',
      'record',
      'init',
      'with',
      'required',
      'scoped',
    ],
    typeKeywords: [
      'bool',
      'byte',
      'char',
      'decimal',
      'double',
      'float',
      'int',
      'long',
      'object',
      'sbyte',
      'short',
      'string',
      'uint',
      'ulong',
      'ushort',
      'void',
      'Vector2',
      'Vector3',
      'Vector4',
      'Color',
      'Vertex2D',
      'VertexList',
      'List',
      'MathHelper',
      'MathF',
      'PrimitiveType',
      'Texture2D',
      'GraphicsDevice',
      'Main',
      'Commons',
      'ModAsset',
      'Assets',
      'Textures',
      'Matrix',
      'Rectangle',
    ],
    builtins: [
      'Add',
      'ToArray',
      'Count',
      'RotatedBy',
      'Lerp',
      'White',
      'Black',
      'Transparent',
      'DrawUserPrimitives',
      'Value',
      'Get',
      'Sin',
      'Cos',
      'Abs',
      'Sqrt',
      'Min',
      'Max',
      'Floor',
      'Ceiling',
      'TwoPi',
      'Pi',
      'PiOver2',
      'TriangleStrip',
      'TriangleList',
      'Draw',
      'DrawRing',
      'iTime',
      'iResolution',
      'iMouse',
      'graphics',
    ],
    operators: [
      '=',
      '>',
      '<',
      '!',
      '~',
      '?',
      ':',
      '==',
      '<=',
      '>=',
      '!=',
      '&&',
      '||',
      '++',
      '--',
      '+',
      '-',
      '*',
      '/',
      '&',
      '|',
      '^',
      '%',
      '<<',
      '>>',
      '+=',
      '-=',
      '*=',
      '/=',
      '=>',
      '??',
      '?.',
      '??=',
    ],
    symbols: /[=><!~?:&|+\-*/^%]+/,
    escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
    tokenizer: {
      root: [
        // member access: .Name
        [
          /(\.)([A-Z_]\w*)/i,
          [
            'delimiter',
            {
              cases: {
                '@typeKeywords': 'type',
                '@builtins': 'predefined',
                '@default': 'predefined',
              },
            },
          ],
        ],
        // function-like identifiers before (
        [
          /[A-Z_]\w*(?=\s*[<(])/i,
          {
            cases: {
              '@keywords': 'keyword',
              '@typeKeywords': 'type',
              '@builtins': 'predefined',
              '@default': 'predefined',
            },
          },
        ],
        [
          /[A-Z_]\w*/i,
          {
            cases: {
              '@keywords': 'keyword',
              '@typeKeywords': 'type',
              '@builtins': 'predefined',
              '@default': 'identifier',
            },
          },
        ],
        { include: '@whitespace' },
        [/[{}()[\]]/, '@brackets'],
        [/[<>](?!@symbols)/, '@brackets'],
        [
          /@symbols/,
          {
            cases: {
              '@operators': 'operator',
              '@default': '',
            },
          },
        ],
        [/\d*\.\d+(e[-+]?\d+)?[fdm]?/i, 'number.float'],
        [/\d+e[-+]?\d+[fdm]?/i, 'number.float'],
        [/\d+[fdm]/i, 'number.float'],
        [/0x[0-9a-f_]+[ul]*/i, 'number.hex'],
        [/\d+[ul]*/i, 'number'],
        [/[;,]/, 'delimiter'],
        [/"([^"\\]|\\.)*$/, 'string.invalid'],
        [/"/, 'string', '@string'],
        [/'[^\\']'/, 'string'],
        [/(')(@escapes)(')/, ['string', 'string.escape', 'string']],
        [/'/, 'string.invalid'],
      ],
      whitespace: [
        [/[ \t\r\n]+/, 'white'],
        [/\/\*/, 'comment', '@comment'],
        [/\/\/.*$/, 'comment'],
      ],
      comment: [
        [/[^/*]+/, 'comment'],
        [/\*\//, 'comment', '@pop'],
        [/[/*]/, 'comment'],
      ],
      string: [
        [/[^\\"]+/, 'string'],
        [/@escapes/, 'string.escape'],
        [/\\./, 'string.escape.invalid'],
        [/"/, 'string', '@pop'],
      ],
    },
  })
}
