name: Deploy to Server
run-name: ${{ github.actor }} is deploying a new version to the development server

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.18.0
  BASE_URL: ${{ vars.BASE_URL }}
  COLOR_MODE_STORAGE_KEY: ${{ vars.COLOR_MODE_STORAGE_KEY }}
  LANGUAGE_STORAGE_KEY: ${{ vars.LANGUAGE_STORAGE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.18.0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: pnpm

      - name: Pnpm Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Deploy to server
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: '-avz --delete'
          SOURCE: '.output/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
